### ISSUE TITLE
To Help Prevent Confusion

### ISSUE THREAD

**Issue by ghost** [crewmate-srv/crewmate#1]
To help prevent confusion between my server and your server, I'd like to request adding stuff like a link to your issues page in your server software so I don't get your bug reports. I'll be doing the same.

My server is at https://github.com/alexis-evelyn/CrewMate

**Comment by BrightSkyz** [comment]
That sounds alright with me. I'll add it in a message in the console when it starts up. I'll update this issue when it has been completed.

**Comment by BrightSkyz** [comment]
Solved in commit 282d325
